name: Build and Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set dynamic tag
        id: set_tag
        run: echo "TAG_NAME=v$(date +'%Y%m%d-%H%M')" >> $GITHUB_ENV

      - name: Build executables
        run: |
          pyinstaller --onefile --name gcz-linux main.py
          pyinstaller --onefile --name gcz-windows.exe main.py
          mkdir -p dist
          mv gcz-linux dist/
          mv gcz-windows.exe dist/

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.TAG_NAME }}  # Usa el tag dinámico
          name: "Release ${{ env.TAG_NAME }}"
          body: "🚀 New automatic release generated from main branch."
          files: |
            dist/gcz-linux
            dist/gcz-windows.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUBTOKEN }}
          RELEASE_VERSION: ${{ secrets.VERSIONRELEASE }}
